FROM node:16.15.0
WORKDIR /usr/src/app

# prismaの設定
# RUN npm install prisma
# ## 初回のみ実行
# RUN npx prisma init 

# # expressの設定
# RUN npm install express cors
# npm install -D nodemon

# # 初回のみ実行
# RUN npx prisma init 